### ISSUE TITLE
18887 segmentation fault (core dumped)

### ISSUE THREAD

**Issue by yongzhiyang2012** [xflouris/bpp#52]
I have download the bpp software and installed correctly.
When testing the software with the example dataset ChenLi2001.txt (in the raw bbp software, http://abacus.gene.ucl.ac.uk/software/bpp4.0.tgz), I got some errors.
The tree file test.tree just cntained a newick tree: (((H, C), G), O);
runing code and following errors:
`bpp --stree_file test.tree --msa_file ChenLi2001.txt --map_file ChenLi2001.Imap.txt --output_file out.txt --mcmc_file mcmc.txt`

bpp

v0.1.0_linux_x86_64, 63GB RAM, 32 cores
https://github.com/xflouris/bpp

Detected CPU features: mmx sse sse2 sse3 ssse3 sse4.1 sse4.2 popcnt avx
Auto-selected SIMD ISA: AVX

Parsing species tree... Done
Parsing phylip file... Done
... ... 
Map of populations and ancestors (1 in map indicates ancestor):
  Species   0  1  2  3  4  5  6
0 H         1  0  0  0  1  1  1
1 C         0  1  0  0  1  1  1
2 G         0  0  1  0  1  1  0
3 O         0  0  0  1  1  0  0
4 HCGO      0  0  0  0  1  0  0
5 HCG       0  0  0  0  1  1  0
6 HC        0  0  0  0  1  1  1

[1]    18887 segmentation fault (core dumped) bpp --stree_file test.tree --msa_file ChenLi2001.txt --map_file 

Can anyone help me? Thanks.

**Comment by xflouris** [comment]
Hello @yongzhiyang2012 ,
sorry for the very late reply. 

I haven't yet removed the legacy command-line switches, but I will do that this week. The right way to run this new version of BPP is using the `--cfile` switch. In your case, that would be:

`bpp --cfile ChenLi2001.bpp.ctl`

I'm not sure what the problem was with the segmentation fault, but definitely some required command-line switch was missing. I have stopped maintaining the command-line arguments for a maybe a month or two.

Thanks for the feedback, I'll update the documentation soon.

Tomas

**Comment by yongzhiyang2012** [comment]
Thank you for replying. I will try this. yangyongzhi2008 邮箱：yangyongzhi2008@gmail.com 签名由 网易邮箱大师 定制 在2018年01月03日 19:30，Tomas Flouri 写道： Hello @yongzhiyang2012 , sorry for the very late reply. I haven't yet removed the legacy command-line switches, but I will do that this week. The right way to run this new version of BPP is using the --cfile switch. In your case, that would be: bpp --cfile ChenLi2001.bpp.ctl I'm not sure what the problem was with the segmentation fault, but definitely some required command-line switch was missing. I have stopped maintaining the command-line arguments for a maybe a month or two. Thanks for the feedback, I'll update the documentation soon. Tomas — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by xflouris** [comment]
Just FYI: methods A00, A01 and A10 should work fine.  A11 (species tree inference + delimitation) is not yet added. Population sizes are always computed (cannot be integrated out), some options are still not added (locusrate and heredity), but I will be creating a first release version with all these options implemented by end of next week.

Let me know if you run into problems.

**Comment by xflouris** [comment]
All methods (A00/A01/A10/A11) are now part of the new bpp.
