### ISSUE TITLE
Add vectorized likelihood function

### ISSUE THREAD

**Issue by xflouris** [xflouris/bpp#6]
Add vectorized (SSE and AVX) likelihood function for the JC69 substitution matrix.

**Comment by ziheng-yang** [comment]
Dear Tomas,
If this works with bpp4, could you send me a copy of the sse and avx functions, so I will replace my old copy?
Thanks,
Ziheng


On 15 Nov 2016, at 16:33, Tomas Flouri <notifications@github.com<mailto:notifications@github.com>> wrote:


Add vectorized (SSE and AVX) likelihood function for the JC69 substitution matrix.

-

**Comment by xflouris** [comment]
finished
