### ISSUE TITLE
Setup initial species tree (A00)

### ISSUE THREAD

**Issue by xflouris** [xflouris/bpp#8]
After loading the species tree from newick format and creating the tree structure set the following the &tau; and &theta; parameters.

## &tau;

For each inner node of the species tree we set one age (&tau;). Root node age and other inner node ages are setup differently:

root-node-age = (&beta; / (&alpha;-1))&times; (0.9 + 0.2&times; _U_)
inner-node-age = propr + (1 - prop - 0.02)&times; _U_

where _U_ is a value between (0,1) obtained from a uniform pseudo-random number generator.

## &theta;

Set the theta at each inner node of the species tree that represents a population (extinct + all extant species that have at least 2 sequences at some loci).

node-theta = (&beta; (&alpha;-1))&times; (0.9 + 0.2&times;_U_)

**Comment by ziheng-yang** [comment]
Beta/(alpha - 1) is the mean of the inverse gamma.
Theta's are initialised with a value around the prior mean.
Tau_0 for the root has the inverse gamma prior and is initialised at a value close to the prior mean.  Other tau's must be younger.  They have a prior that is more or less uniform between 0 and tau_0, and each is initialised by a value that is a fraction of the tau for the mother node.  This works ok but is not perfect.
Ziheng




On 16 Nov 2016, at 11:12, Tomas Flouri <notifications@github.com<mailto:notifications@github.com>> wrote:
After loading the species tree from newick format and creating the tree structure set the following the ? and ? parameters.
?

For each inner node of the species tree we set one age (?). Root node age and other inner node ages are setup differently:

root-node-age = (? / (?-1))? (0.9 + 0.2? U)
inner-node-age = propr + (1 - prop - 0.02)? U

where U is a value between (0,1) obtained from a uniform pseudo-random number generator.

?

Set the theta at each inner node of the species tree that represents a population (extinct + all extant species that have at least 2 sequences at some loci).

node-theta = (? (?-1))? (0.9 + 0.2?U)

-

**Comment by xflouris** [comment]
finished
